<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_DESCRIPTION</name>
   <tag></tag>
   <elementGuidId>7b76599a-513a-4f3a-9d76-25a8286d909d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.cart_desc_label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cart_contents_container']/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9beb1e72-0912-4e9d-8b04-cfcf83e613be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cart_desc_label</value>
      <webElementGuid>8ad41dd0-c79f-4e1a-8330-4812534d33c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DESCRIPTION</value>
      <webElementGuid>380f6d21-2eef-444f-8252-b5e8b0f10c6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart_contents_container&quot;)/div[1]/div[@class=&quot;cart_list&quot;]/div[@class=&quot;cart_desc_label&quot;]</value>
      <webElementGuid>626e23e7-ac1c-4234-b130-73a3850bab78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cart_contents_container']/div/div/div[2]</value>
      <webElementGuid>bfe495e2-7ba2-43b9-83e0-819a5af32bec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]</value>
      <webElementGuid>e71698be-8185-43c3-977b-e6ba57c7cdc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'DESCRIPTION' or . = 'DESCRIPTION')]</value>
      <webElementGuid>97a4b3d7-fc16-4f8b-b203-5be62690cb55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
